package br.com.leandromoreira.chip16.ui;

import br.com.leandromoreira.chip16.Chip16Machine;
import br.com.leandromoreira.chip16.Chip16MainLoop;
import br.com.leandromoreira.chip16.debug.Breakpoint;
import br.com.leandromoreira.chip16.debug.Debugger;
import br.com.leandromoreira.chip16.gpu.Java2DRender;
import br.com.leandromoreira.chip16.util.ConfigManager;
import br.com.leandromoreira.chip16.util.JavaEmuUtil;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JFileChooser;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 * @author leandro-rm
 */
public class Main extends javax.swing.JFrame {

    /** Creates new form Main */
    public Main() {
        initComponents();
    }

    private void fillAssembler(final int start) {
        setupJTable();
        int row = 0, addressColunm = 1, codeColunm = 2;
        List<Chip16Machine.Assembler> machineCode = machine.getAssembler(start);
        for (Chip16Machine.Assembler assembler : machineCode) {
            jTblAssembler.setValueAt(JavaEmuUtil.getHexadecimal4Formatted(assembler.getPc()).substring(2), row, addressColunm);
            jTblAssembler.setValueAt(assembler.getLine(), row, codeColunm);
            row++;
        }
    }

    private void fillMemory() {
        jTxtMemory.setText(machine.getFormattedMemory());
        jTxtMemory.setCaretPosition(0);
    }

    private void handleShortCuts(KeyEvent evt) {
        if (evt.getKeyCode() == 117) {
            jBtnStepActionPerformed(null);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtMemory = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtR0 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtR1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtR2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtR3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtR4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtR5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtRC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtRA = new javax.swing.JTextField();
        jTxtRD = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtR9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtR8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxtRB = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTxtR6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTxtR7 = new javax.swing.JTextField();
        jTxtRE = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTxtRF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTxtPC = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTxtSP = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jChkV = new javax.swing.JCheckBox();
        jChkC = new javax.swing.JCheckBox();
        jChkZ = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jTxtMW00 = new javax.swing.JTextField();
        jTxtMW0 = new javax.swing.JTextField();
        jTxtMW01 = new javax.swing.JTextField();
        jTxtMW1 = new javax.swing.JTextField();
        jTxtMW02 = new javax.swing.JTextField();
        jTxtMW2 = new javax.swing.JTextField();
        jTxtMW03 = new javax.swing.JTextField();
        jTxtMW3 = new javax.swing.JTextField();
        jTxtMW04 = new javax.swing.JTextField();
        jTxtMW4 = new javax.swing.JTextField();
        jTxtMW05 = new javax.swing.JTextField();
        jTxtMW5 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtStackList = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblAssembler = new javax.swing.JTable();
        jBtnSetBreakpoint = new javax.swing.JButton();
        jBtnStep = new javax.swing.JButton();
        jPnScreen = new javax.swing.JPanel();
        jBtnRemoveBreak = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTxtGPU = new javax.swing.JTextArea();
        jBtnLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                opening(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keyRelesead(evt);
            }
        });

        jLblInfo.setFont(new java.awt.Font("Ubuntu", 1, 15));
        jLblInfo.setForeground(new java.awt.Color(90, 87, 184));
        jLblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jScrollPane1.setBackground(new java.awt.Color(22, 18, 14));

        jTxtMemory.setBackground(new java.awt.Color(6, 6, 6));
        jTxtMemory.setColumns(8);
        jTxtMemory.setEditable(false);
        jTxtMemory.setForeground(new java.awt.Color(51, 192, 70));
        jTxtMemory.setRows(5);
        jScrollPane1.setViewportView(jTxtMemory);

        jLabel1.setText("Memory Viewer");

        jLabel2.setText("Registers");

        jLabel3.setText("0");

        jTxtR0.setBackground(new java.awt.Color(10, 6, 2));
        jTxtR0.setEditable(false);
        jTxtR0.setForeground(new java.awt.Color(35, 245, 97));
        jTxtR0.setText("0000");

        jLabel4.setText("1");

        jTxtR1.setBackground(new java.awt.Color(10, 6, 2));
        jTxtR1.setEditable(false);
        jTxtR1.setForeground(new java.awt.Color(35, 245, 97));
        jTxtR1.setText("0000");

        jLabel5.setText("2");

        jTxtR2.setBackground(new java.awt.Color(10, 6, 2));
        jTxtR2.setEditable(false);
        jTxtR2.setForeground(new java.awt.Color(35, 245, 97));
        jTxtR2.setText("0000");

        jLabel6.setText("3");

        jTxtR3.setBackground(new java.awt.Color(10, 6, 2));
        jTxtR3.setEditable(false);
        jTxtR3.setForeground(new java.awt.Color(35, 245, 97));
        jTxtR3.setText("0000");

        jLabel7.setText("4");

        jTxtR4.setBackground(new java.awt.Color(10, 6, 2));
        jTxtR4.setEditable(false);
        jTxtR4.setForeground(new java.awt.Color(35, 245, 97));
        jTxtR4.setText("0000");

        jLabel8.setText("5");

        jTxtR5.setBackground(new java.awt.Color(10, 6, 2));
        jTxtR5.setEditable(false);
        jTxtR5.setForeground(new java.awt.Color(35, 245, 97));
        jTxtR5.setText("0000");

        jLabel9.setText("B");

        jTxtRC.setBackground(new java.awt.Color(10, 6, 2));
        jTxtRC.setEditable(false);
        jTxtRC.setForeground(new java.awt.Color(35, 245, 97));
        jTxtRC.setText("0000");

        jLabel10.setText("A");

        jLabel11.setText("D");

        jTxtRA.setBackground(new java.awt.Color(10, 6, 2));
        jTxtRA.setEditable(false);
        jTxtRA.setForeground(new java.awt.Color(35, 245, 97));
        jTxtRA.setText("0000");

        jTxtRD.setBackground(new java.awt.Color(10, 6, 2));
        jTxtRD.setEditable(false);
        jTxtRD.setForeground(new java.awt.Color(35, 245, 97));
        jTxtRD.setText("0000");

        jLabel12.setText("9");

        jTxtR9.setBackground(new java.awt.Color(10, 6, 2));
        jTxtR9.setEditable(false);
        jTxtR9.setForeground(new java.awt.Color(35, 245, 97));
        jTxtR9.setText("0000");

        jLabel13.setText("8");

        jTxtR8.setBackground(new java.awt.Color(10, 6, 2));
        jTxtR8.setEditable(false);
        jTxtR8.setForeground(new java.awt.Color(35, 245, 97));
        jTxtR8.setText("0000");

        jLabel14.setText("C");

        jTxtRB.setBackground(new java.awt.Color(10, 6, 2));
        jTxtRB.setEditable(false);
        jTxtRB.setForeground(new java.awt.Color(35, 245, 97));
        jTxtRB.setText("0000");

        jLabel15.setText("E");

        jLabel16.setText("6");

        jTxtR6.setBackground(new java.awt.Color(10, 6, 2));
        jTxtR6.setEditable(false);
        jTxtR6.setForeground(new java.awt.Color(35, 245, 97));
        jTxtR6.setText("0000");

        jLabel17.setText("7");

        jTxtR7.setBackground(new java.awt.Color(10, 6, 2));
        jTxtR7.setEditable(false);
        jTxtR7.setForeground(new java.awt.Color(35, 245, 97));
        jTxtR7.setText("0000");

        jTxtRE.setBackground(new java.awt.Color(10, 6, 2));
        jTxtRE.setEditable(false);
        jTxtRE.setForeground(new java.awt.Color(35, 245, 97));
        jTxtRE.setText("0000");

        jLabel18.setText("F");

        jTxtRF.setBackground(new java.awt.Color(10, 6, 2));
        jTxtRF.setEditable(false);
        jTxtRF.setForeground(new java.awt.Color(35, 245, 97));
        jTxtRF.setText("0000");

        jLabel19.setText("PC:");

        jTxtPC.setBackground(new java.awt.Color(10, 6, 2));
        jTxtPC.setEditable(false);
        jTxtPC.setForeground(new java.awt.Color(35, 245, 97));
        jTxtPC.setText("0000");

        jLabel20.setText("SP:");

        jTxtSP.setBackground(new java.awt.Color(10, 6, 2));
        jTxtSP.setEditable(false);
        jTxtSP.setForeground(new java.awt.Color(35, 245, 97));
        jTxtSP.setText("0000");

        jLabel21.setText("Flag:");

        jChkV.setText("V");

        jChkC.setText("C");

        jChkZ.setText("Z");
        jChkZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkZActionPerformed(evt);
            }
        });

        jCheckBox4.setText("R");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("R");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setText("R");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setText("R");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setText("R");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jLabel22.setText("Memory Watcher");

        jTxtMW00.setBackground(new java.awt.Color(10, 6, 2));
        jTxtMW00.setForeground(new java.awt.Color(32, 243, 46));
        jTxtMW00.setText("0000");

        jTxtMW0.setBackground(new java.awt.Color(10, 6, 2));
        jTxtMW0.setEditable(false);
        jTxtMW0.setForeground(new java.awt.Color(23, 243, 29));
        jTxtMW0.setText("0000");

        jTxtMW01.setBackground(new java.awt.Color(10, 6, 2));
        jTxtMW01.setForeground(new java.awt.Color(32, 243, 46));
        jTxtMW01.setText("0000");

        jTxtMW1.setBackground(new java.awt.Color(10, 6, 2));
        jTxtMW1.setEditable(false);
        jTxtMW1.setForeground(new java.awt.Color(23, 243, 29));
        jTxtMW1.setText("0000");

        jTxtMW02.setBackground(new java.awt.Color(10, 6, 2));
        jTxtMW02.setForeground(new java.awt.Color(32, 243, 46));
        jTxtMW02.setText("0000");

        jTxtMW2.setBackground(new java.awt.Color(10, 6, 2));
        jTxtMW2.setEditable(false);
        jTxtMW2.setForeground(new java.awt.Color(23, 243, 29));
        jTxtMW2.setText("0000");

        jTxtMW03.setBackground(new java.awt.Color(10, 6, 2));
        jTxtMW03.setForeground(new java.awt.Color(32, 243, 46));
        jTxtMW03.setText("0000");

        jTxtMW3.setBackground(new java.awt.Color(10, 6, 2));
        jTxtMW3.setEditable(false);
        jTxtMW3.setForeground(new java.awt.Color(23, 243, 29));
        jTxtMW3.setText("0000");

        jTxtMW04.setBackground(new java.awt.Color(10, 6, 2));
        jTxtMW04.setForeground(new java.awt.Color(32, 243, 46));
        jTxtMW04.setText("0000");

        jTxtMW4.setBackground(new java.awt.Color(10, 6, 2));
        jTxtMW4.setEditable(false);
        jTxtMW4.setForeground(new java.awt.Color(23, 243, 29));
        jTxtMW4.setText("0000");

        jTxtMW05.setBackground(new java.awt.Color(10, 6, 2));
        jTxtMW05.setForeground(new java.awt.Color(32, 243, 46));
        jTxtMW05.setText("0000");

        jTxtMW5.setBackground(new java.awt.Color(10, 6, 2));
        jTxtMW5.setEditable(false);
        jTxtMW5.setForeground(new java.awt.Color(23, 243, 29));
        jTxtMW5.setText("0000");

        jLabel23.setText("Stack List");

        jScrollPane2.setBackground(new java.awt.Color(22, 18, 14));

        jTxtStackList.setBackground(new java.awt.Color(6, 6, 6));
        jTxtStackList.setColumns(4);
        jTxtStackList.setEditable(false);
        jTxtStackList.setForeground(new java.awt.Color(51, 192, 70));
        jTxtStackList.setRows(5);
        jScrollPane2.setViewportView(jTxtStackList);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("run-project-btn.png"))); // NOI18N
        jButton1.setText("Run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("debug-project-btn.png"))); // NOI18N
        jButton2.setText("Debug");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTblAssembler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblAssembler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                breakpoint(evt);
            }
        });
        jTblAssembler.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTblAssemblerKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTblAssembler);

        jBtnSetBreakpoint.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("breakpoint-badge.png"))); // NOI18N
        jBtnSetBreakpoint.setText("Set Break.");
        jBtnSetBreakpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSetBreakpointActionPerformed(evt);
            }
        });

        jBtnStep.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("step-over-btn.png"))); // NOI18N
        jBtnStep.setText("Step");
        jBtnStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStepActionPerformed(evt);
            }
        });
        jBtnStep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBtnStepKeyReleased(evt);
            }
        });

        jPnScreen.setBackground(new java.awt.Color(1, 1, 1));
        jPnScreen.setPreferredSize(new java.awt.Dimension(320, 240));
        jPnScreen.setRequestFocusEnabled(false);
        jPnScreen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pressed(evt);
            }
        });

        javax.swing.GroupLayout jPnScreenLayout = new javax.swing.GroupLayout(jPnScreen);
        jPnScreen.setLayout(jPnScreenLayout);
        jPnScreenLayout.setHorizontalGroup(
            jPnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPnScreenLayout.setVerticalGroup(
            jPnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jBtnRemoveBreak.setText("Remove Break.");
        jBtnRemoveBreak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoveBreakActionPerformed(evt);
            }
        });
        jBtnRemoveBreak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                joypadPressing(evt);
            }
        });

        jTxtGPU.setBackground(java.awt.Color.black);
        jTxtGPU.setColumns(20);
        jTxtGPU.setEditable(false);
        jTxtGPU.setForeground(new java.awt.Color(31, 243, 74));
        jTxtGPU.setRows(5);
        jScrollPane4.setViewportView(jTxtGPU);

        jBtnLoad.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("open-project-btn.png"))); // NOI18N
        jBtnLoad.setText("Load");
        jBtnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoadActionPerformed(evt);
            }
        });
        jBtnLoad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBtnLoadKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtR0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(2, 2, 2)
                                                        .addComponent(jLabel4)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(2, 2, 2)
                                                        .addComponent(jLabel5)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(jLabel6)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtR3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(3, 3, 3)
                                                        .addComponent(jLabel7)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtR4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(jLabel8)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtR5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtR8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(2, 2, 2)
                                                        .addComponent(jLabel12)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtR9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(2, 2, 2)
                                                        .addComponent(jLabel10)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(jLabel9)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(3, 3, 3)
                                                        .addComponent(jLabel14)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(jLabel11)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtRD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(3, 3, 3)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel16)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtR6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(jLabel17)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtR7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel15)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(jLabel18)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jTxtRF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(91, 91, 91)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jCheckBox5)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel19)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(jTxtPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel20)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(jTxtSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel21)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jChkV)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jChkC)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jChkZ)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jCheckBox4))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jCheckBox6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jCheckBox7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jCheckBox8))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(111, 111, 111)
                                        .addComponent(jLabel2)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtMW00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtMW0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtMW03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtMW3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtMW01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtMW1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtMW04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtMW4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtMW02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtMW2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtMW05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtMW5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jBtnLoad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnSetBreakpoint)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnRemoveBreak)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBtnStep))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPnScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTxtR0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtR3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtR4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtR5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTxtR8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtR9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtRD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jChkV)
                                    .addComponent(jChkC)
                                    .addComponent(jChkZ)
                                    .addComponent(jCheckBox4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox5)
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox7)
                                    .addComponent(jCheckBox8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTxtR6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtR7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTxtRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtRF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jBtnSetBreakpoint)
                            .addComponent(jBtnStep)
                            .addComponent(jBtnRemoveBreak)
                            .addComponent(jBtnLoad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPnScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtMW00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtMW0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtMW03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtMW3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtMW01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtMW1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtMW04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtMW4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtMW02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtMW2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtMW05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtMW5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Chip16Machine machine;
    private Debugger debugger;

    private void opening(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_opening
        try {
            debugger = new Debugger();
            machine = new Chip16Machine(new File("rom/ROMs/Demos/ASCII.c16"));
            setTitle(ConfigManager.getConfig().getTitle() + " --> " + machine.getRom().getTitleName());
            jLblInfo.setText(ConfigManager.getConfig().getVMHeader());
            fillRegisters();
            fillFlags();
            fillMemory();
            fillStack();
            fillAssembler(0);
            fillMemoryWatch();
            jPnScreen.setDoubleBuffered(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_opening

    private void jChkZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkZActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void keyRelesead(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyRelesead
        handleShortCuts(evt);
    }//GEN-LAST:event_keyRelesead
    private boolean showAssemblerOnConsole = false;

    private void jBtnStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStepActionPerformed
        try {
            machine.debugStep(new Java2DRender(jPnScreen.getGraphics().create()));
            moveCursor(Integer.valueOf(machine.getCPUInfo().getPC(), 16));
            fillRegisters();
            fillStack();
            fillFlags();
            fillGPU();
            fillMemoryWatch();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro while debugging --> " + e.toString());
        }
    }//GEN-LAST:event_jBtnStepActionPerformed
    private int tries = 0;

    private void moveCursor(int row) {
        try {
            boolean findRowCursor = false;
            int rowNumber = jTblAssembler.getRowCount();
            for (int i = 0; i < rowNumber; i++) {
                if (Integer.valueOf(jTblAssembler.getValueAt(i, 1).toString(), 16) == (row)) {
                    row = i;
                    findRowCursor = true;
                    break;
                }
            }
            if (findRowCursor) {
                jTblAssembler.setRowSelectionInterval(row, row);
                scrollToCenter(jTblAssembler, row, 2);
                tries = 0;
                if (showAssemblerOnConsole) {
                    System.out.println(jTblAssembler.getValueAt(row, 2));
                }
            } else {
                if (tries >= 3) {
                    JOptionPane.showMessageDialog(this, "Debugger system wasn't capable to find the actual line. [" + JavaEmuUtil.getHexadecimal4Formatted(row) + "]");
                } else {
                    fillAssembler(row);
                    moveCursor(row);
                    tries++;
                }
            }
        } catch (java.lang.NullPointerException ex) {
                if (tries >= 3) {
                    JOptionPane.showMessageDialog(this, "Debugger system wasn't capable to find the actual line. [" + JavaEmuUtil.getHexadecimal4Formatted(row) + "]");
                } else {
                    fillAssembler(row);
                    moveCursor(row);
                    tries++;
                }
            //JOptionPane.showMessageDialog(this, "Debugger system wasn't capable to find the actual line. ["+ JavaEmuUtil.getHexadecimal4Formatted(row) + "]");
        }
    }

    public static void scrollToCenter(JTable table, int rowIndex, int vColIndex) {
        if (!(table.getParent() instanceof JViewport)) {
            return;
        }
        JViewport viewport = (JViewport) table.getParent();
        Rectangle rect = table.getCellRect(rowIndex, vColIndex, true);
        Rectangle viewRect = viewport.getViewRect();
        rect.setLocation(rect.x - viewRect.x, rect.y - viewRect.y);

        int centerX = (viewRect.width - rect.width) / 2;
        int centerY = (viewRect.height - rect.height) / 2;

        if (rect.x < centerX) {
            centerX = -centerX;
        }
        if (rect.y < centerY) {
            centerY = -centerY;
        }
        rect.translate(centerX, centerY);
        viewport.scrollRectToVisible(rect);
    }

    private void jBtnSetBreakpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSetBreakpointActionPerformed
        try {
            int rowIndex = jTblAssembler.getSelectedRow();
            jTblAssembler.setValueAt(Debugger.DEBUGGER_CHR, rowIndex, 0);
            int addressInstruction = Integer.valueOf(jTblAssembler.getValueAt(rowIndex, 1).toString().substring(2), 16);
            debugger.add(new Breakpoint(addressInstruction));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jBtnSetBreakpointActionPerformed

    private void jBtnRemoveBreakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoveBreakActionPerformed
        try {
            int rowIndex = jTblAssembler.getSelectedRow();
            jTblAssembler.setValueAt("", rowIndex, 0);
            int addressInstruction = Integer.valueOf(jTblAssembler.getValueAt(rowIndex, 1).toString().substring(2), 16);
            debugger.remove(new Breakpoint(addressInstruction));
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jBtnRemoveBreakActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        System.out.println(evt);
    }//GEN-LAST:event_formKeyPressed

    private void jTblAssemblerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblAssemblerKeyReleased
    }//GEN-LAST:event_jTblAssemblerKeyReleased

    private void jBtnStepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnStepKeyReleased
        handleShortCuts(evt);
    }//GEN-LAST:event_jBtnStepKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         //new Thread(new Chip16MainLoop(machine, new Java2DRender(jPnScreen.getGraphics().create())),).start();
        /*new Thread(new Runnable() {

            @Override
            public void run() {
                while(true){
                    machine.cpuStep();
                }
            }
        }).start();
        new Thread(new Runnable() {
            @Override
            public void run() {
                final Render r = new Java2DRender(jPnScreen.getGraphics().create());
                while(true){
                    machine.drawFrame(r);
                    try {
                        Thread.sleep(1000/60);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();*/
        
    }//GEN-LAST:event_jButton1ActionPerformed
    private int x = 0, y = 0;

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void breakpoint(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_breakpoint
        
    }//GEN-LAST:event_breakpoint

    private void jBtnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoadActionPerformed
      final JFileChooser chooseARom = new JFileChooser(new File("./rom/ROMs"));

      int whatUserDid = chooseARom.showOpenDialog(this);
      if (whatUserDid == JFileChooser.APPROVE_OPTION) {
        File romFile = chooseARom.getSelectedFile();
        try {
          debugger = new Debugger();
          machine = new Chip16Machine(romFile);
          setTitle(ConfigManager.getConfig().getTitle() + " --> " + machine.getRom().getTitleName());
          jLblInfo.setText(ConfigManager.getConfig().getVMHeader());
          fillRegisters();
          fillFlags();
          fillMemory();
          fillStack();
          fillAssembler(0);
          fillMemoryWatch();
          jPnScreen.setDoubleBuffered(true);
        } catch (Exception e) {
          e.printStackTrace();
          JOptionPane.showMessageDialog(this, e.toString());
        }
      }


      // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLoadActionPerformed

    private void jBtnLoadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnLoadKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLoadKeyReleased

    private void pressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pressed
        // TODO add your handling code here:
        System.out.println(evt);
    }//GEN-LAST:event_pressed

    private void joypadPressing(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_joypadPressing
        // TODO add your handling code here:
        System.out.println(evt);
    }//GEN-LAST:event_joypadPressing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLoad;
    private javax.swing.JButton jBtnRemoveBreak;
    private javax.swing.JButton jBtnSetBreakpoint;
    private javax.swing.JButton jBtnStep;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jChkC;
    private javax.swing.JCheckBox jChkV;
    private javax.swing.JCheckBox jChkZ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblInfo;
    private javax.swing.JPanel jPnScreen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTblAssembler;
    private javax.swing.JTextArea jTxtGPU;
    private javax.swing.JTextField jTxtMW0;
    private javax.swing.JTextField jTxtMW00;
    private javax.swing.JTextField jTxtMW01;
    private javax.swing.JTextField jTxtMW02;
    private javax.swing.JTextField jTxtMW03;
    private javax.swing.JTextField jTxtMW04;
    private javax.swing.JTextField jTxtMW05;
    private javax.swing.JTextField jTxtMW1;
    private javax.swing.JTextField jTxtMW2;
    private javax.swing.JTextField jTxtMW3;
    private javax.swing.JTextField jTxtMW4;
    private javax.swing.JTextField jTxtMW5;
    private javax.swing.JTextArea jTxtMemory;
    private javax.swing.JTextField jTxtPC;
    private javax.swing.JTextField jTxtR0;
    private javax.swing.JTextField jTxtR1;
    private javax.swing.JTextField jTxtR2;
    private javax.swing.JTextField jTxtR3;
    private javax.swing.JTextField jTxtR4;
    private javax.swing.JTextField jTxtR5;
    private javax.swing.JTextField jTxtR6;
    private javax.swing.JTextField jTxtR7;
    private javax.swing.JTextField jTxtR8;
    private javax.swing.JTextField jTxtR9;
    private javax.swing.JTextField jTxtRA;
    private javax.swing.JTextField jTxtRB;
    private javax.swing.JTextField jTxtRC;
    private javax.swing.JTextField jTxtRD;
    private javax.swing.JTextField jTxtRE;
    private javax.swing.JTextField jTxtRF;
    private javax.swing.JTextField jTxtSP;
    private javax.swing.JTextArea jTxtStackList;
    // End of variables declaration//GEN-END:variables

    private void fillStack() {
        jTxtStackList.setText(machine.getFormattedStack());
    }

    private void setupJTable() {
        jTblAssembler.setModel(new DefaultTableModel(new String[]{"", "Address", "Code"}, 0x7FFF));
        jTblAssembler.getColumnModel().getColumn(0).setMaxWidth(5);
        jTblAssembler.getColumnModel().getColumn(0).setResizable(false);
        jTblAssembler.getColumnModel().getColumn(1).setResizable(false);
        jTblAssembler.getColumnModel().getColumn(2).setResizable(false);
        jTblAssembler.getColumnModel().getColumn(1).setMaxWidth(60);
        jTblAssembler.getColumnModel().getColumn(1).setCellRenderer(
                new TableCellRenderer() {

                    @Override
                    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                        Component renderer = new DefaultTableCellRenderer().getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                        renderer.setForeground(Color.getHSBColor(Color.RGBtoHSB(0x00, 0x00, 0x66, null)[0], Color.RGBtoHSB(0x00, 0x00, 0x66, null)[1], Color.RGBtoHSB(0x00, 0x00, 0x66, null)[2]));
                        return renderer;
                    }
                });
        jTblAssembler.getColumnModel().getColumn(0).setCellRenderer(
                new TableCellRenderer() {

                    @Override
                    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                        Component renderer = new DefaultTableCellRenderer().getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                        renderer.setForeground(Color.getHSBColor(Color.RGBtoHSB(0xFF, 0x72, 0x46, null)[0], Color.RGBtoHSB(0xFF, 0x72, 0x46, null)[1], Color.RGBtoHSB(0xFF, 0x72, 0x46, null)[2]));
                        return renderer;
                    }
                });

        jTblAssembler.setFocusable(false);
        jTblAssembler.setSelectionBackground(new java.awt.Color(0, 0, 204));
        jTblAssembler.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTblAssembler.setShowHorizontalLines(false);
        jTblAssembler.setShowVerticalLines(false);
    }

    private void fillRegisters() {
        jTxtPC.setText(machine.getCPUInfo().getPC());
        jTxtSP.setText(machine.getCPUInfo().getSP());
        jTxtR0.setText(machine.getCPUInfo().getR0());
        jTxtR1.setText(machine.getCPUInfo().getR1());
        jTxtR2.setText(machine.getCPUInfo().getR2());
        jTxtR3.setText(machine.getCPUInfo().getR3());
        jTxtR4.setText(machine.getCPUInfo().getR4());
        jTxtR5.setText(machine.getCPUInfo().getR5());
        jTxtR6.setText(machine.getCPUInfo().getR6());
        jTxtR7.setText(machine.getCPUInfo().getR7());
        jTxtR8.setText(machine.getCPUInfo().getR8());
        jTxtR9.setText(machine.getCPUInfo().getR9());
        jTxtRA.setText(machine.getCPUInfo().getRA());
        jTxtRB.setText(machine.getCPUInfo().getRB());
        jTxtRC.setText(machine.getCPUInfo().getRC());
        jTxtRD.setText(machine.getCPUInfo().getRD());
        jTxtRE.setText(machine.getCPUInfo().getRE());
        jTxtRF.setText(machine.getCPUInfo().getRF());
    }

    private void fillFlags() {
        jChkC.setSelected(machine.getCPUInfo().getFlagC());
        jChkV.setSelected(machine.getCPUInfo().getFlagV());
        jChkZ.setSelected(machine.getCPUInfo().getFlagZ());
    }

    private void fillGPU() {
        jTxtGPU.setText("GPU --\nBG Color: " + machine.getGPUInfo().getBGColor() + "\nCurrent Sprite: " + machine.getGPUInfo().getCurrentSprite() + machine.getGPUInfo().getSpriteAddress());
    }

    private void fillMemoryWatch() {
        showMemoryExpression(jTxtMW00, jTxtMW0);
        showMemoryExpression(jTxtMW01, jTxtMW1);
        showMemoryExpression(jTxtMW02, jTxtMW2);
        showMemoryExpression(jTxtMW03, jTxtMW3);
        showMemoryExpression(jTxtMW04, jTxtMW4);
        showMemoryExpression(jTxtMW05, jTxtMW5);
    }

    private void showMemoryExpression(JTextField address, JTextField value) {
        try {
            short memoryValue = machine.getMemory().readFrom(Integer.valueOf(address.getText(), 16));
            value.setText(JavaEmuUtil.getHexadecimal2Formatted(memoryValue));
        } catch (Exception e) {
            address.setText("0000");
            value.setText("∞");
        }
    }
}
